### PR TITLE
feat(evolution): gate program fitness on correctness and preserve evidence

### PR DESCRIPTION
**Pull request by ooples**
## Review-readiness audit — September 11, 2026

**Still draft: this foundation is not fully validated.** At `367fce237ac000873f4749e5fcfa6ada4002e9cb`, focused compiler-regressions pass on net8/net10, but Build & Validate, documentation/snippet checks, model-fixture inventory, samples and model-performance workflows report failures; a Vercel website check also fails. Those failures need diagnosis, not dismissal as unrelated without evidence. Compatible published-package integration remains outstanding. The earlier CodeRabbit approval was on another revision. Dependent story PRs continue to build on this foundation; no full-roadmap completion or readiness claim is made.

## Current persistent-fitness slice — 367fce237

- Adds opt-in `PersistentProgramFitnessEvaluator` through `CustomFitnessEvaluator`: exact scope/source identity, age/uncertainty/force-fresh policy, externally verified raw evidence, and separately metered logical store calls. Current correctness still runs before a warm lookup; sample identity/uncertainty and original acquisition cost survive without rebilling.
- Refuses outer engine memoization and uncoordinated checkpoint/resume for the directly configured decorator. Independent engine runs have distinct ledgers and share evidence stores; campaign-wide allocation remains explicit. Oversized source evaluates fresh without persistence.
- Adversarial regressions fixed lost measurement origin in result clones, unsupported LLM blending making a model call, and evidence-verification latency extending freshness. Scripted evidence is control-flow proof, not production raw-evidence storage or a runtime superiority claim.
- **941 focused consumer tests + 79 compiler/worker tests pass separately on net8.0 and net10.0.** New evaluator 89/90 lines; changed production C# 111/112 lines; selected evolution namespace 5,672/6,095 lines. Production/test-copy hashes agree. Normal library builds pass on net8.0/net10.0/net471 with existing warnings; no net471 test run or whole-repository coverage claim.
- Checks in the focused integration test project and runs it against pinned core `76d8343939f9ec1a58c4994384a249e6ecc93dc0` in the companion workflow. Fixes the hosted CLI coverage gate's duplicate TRX attachments: both actual ddad-run reports have identical SHA256 and pass 268/270 benchmark lines; all ten gate tests pass.
- [Consumer contract, Given/When/Then stories, reproduction and evidence](https://github.com/ooples/AiDotNet/blob/367fce237ac000873f4749e5fcfa6ada4002e9cb/docs/evolution-persistent-fitness.md).
- **Current-head hosted validation, independent review and compatible package-path validation remain outstanding.** The published core preview lacks these APIs. This stays draft; the full roadmap and representative warm/cold campaigns are not complete.

## Historical custom-fitness/runtime slice — ddad4e3e7

- Adds `ProgramEvolutionOptions.CustomFitnessEvaluator` through the existing facade. Conflicting scoring configuration is rejected; immutable evaluator identities are checked before/after dispatch. Correctness, descriptors and shared accounting still apply. Minimization explicitly configures the archive direction.
- Adds `aidotnet-evolve benchmark-program`: fixed authored C# catalog, independent public correctness, median end-to-end timing, frozen-winner confirmation, failure-inclusive raw evidence and shared receipts. **No live model, paid service, sealed benchmark or competitor-superiority claim.**
- Retained four-run pilot: **96 dispatched worker calls / 96 units, zero unknown, unchanged listed binary hashes**. Worker startup and compilation are included. The report distinguishes controller runtime from the worker's validated requested configuration; no OS-isolation attestation.
- **901 focused consumer tests + 79 compiler/worker tests pass separately on net8.0 and net10.0; 42 CLI tests pass on net10.0.** New benchmark file: 268/270 executable lines covered; full CLI: 389/463. Custom identity wrapper: 100% line/branch; selected program/options paths: 5,026/5,440 lines and 2,456/3,011 branches (not builder/whole-assembly coverage).
- Library rebuilds pass on net8.0/net10.0/net471 with diagnostic analyzers disabled; no net471 tests claimed. Production/test-copy hashes match. Added a 90% benchmark-file coverage gate with module verification; fixed the invalid literal-hyphen Coverlet filter.
- Hosted d0 source checks failed NU1008 from nested-checkout CPM inheritance; the workflow now uses sibling checkouts. Default-package checks still require a newer compatible Evolution release. **Current-head hosted validation and independent review remain outstanding; the PR stays draft and the full roadmap is not complete.**
- [Workflow, Given/When/Then contracts and verification](https://github.com/ooples/AiDotNet/blob/ddad4e3e71e214ddc5c0fbeb072c9854c57fea64/docs/evolution-runtime-benchmark.md), [complete path-redacted raw pilot](https://github.com/ooples/AiDotNet/blob/ddad4e3e71e214ddc5c0fbeb072c9854c57fea64/docs/benchmarks/authored-runtime-2026-09-11.json).

## Historical execution/evaluator slice — d0c4039ac

- Adds a real offline C# console worker (net8.0/net10.0), compile-only without assembly loading, strict source/image bounds, and a per-worker 256 MiB managed GC ceiling. This is an interpreter, **not filesystem/network containment**.
- Verifies the complete facade → syntax patch → real compiler → child worker → independent correctness/fitness → shared receipts path with authored fixtures and scripted chat. No live model or paid API call was made.
- Fixes 12 first-red regressions: truncated-prefix false passes, asynchronous cancellation/fatal accounting, mutable versioned examples, raw failure payloads labeled redacted, and unused custom-loop legacy provenance sinks. Evaluator compatibility identities changed.
- **888 focused consumer tests + 79 compiler/worker tests pass separately on net8.0 and net10.0.** Both optional/worker coverage runs: 544/550 lines, 365/404 branches. Compiler alone: 98.81% lines / 91.94% branches; worker: 100% / 77.27%. Selected consumer paths: 92.34% / 81.43%, excluding builder and unrelated types. Production/test DLL hashes matched before execution.
- The worker's internal recompilation remains inside whole evaluation-call units; proposal `build_calls` are not claimed as whole-run compiler/CPU/memory totals. No representative optimization or competitor-superiority result is claimed.
- Current-head CI/review, Linux execution and normal compatible NuGet dependency resolution remain outstanding. The .NET Framework 4.7.1 library rebuild succeeded (0 errors); no .NET Framework test run is claimed. Historical CodeRabbit approval was for 75aa6b1d; a later review was skipped at its file-count limit, not approved.
- Contracts, test evidence and remaining limitations: [compiler/worker guide](https://github.com/ooples/AiDotNet/blob/d0c4039ace4046e6cd43b17f67b8e2d1cbebd4d3/docs/evolution-csharp.md), [worker security/setup](https://github.com/ooples/AiDotNet/blob/d0c4039ace4046e6cd43b17f67b8e2d1cbebd4d3/tools/AiDotNet.CSharp.Worker/README.md). The PR remains draft; this does not close all roadmap stories.

## Historical compiler/resource slice — fcb29b770

- Adds optional AiDotNet.Evolution.CSharp (net8.0/net10.0) through ConfigureCSharpProgramEvolution: original-snapshot syntax spans/hashes, protected boundaries, deterministic Roslyn emit, bounded repair and private write-once evidence.
- Adds caller-owned IProgramVariationOperator and ProgramEvolutionResourceOptions. Setup/model/tokens/parse/emit/audit and correctness-plus-fitness use a shared ledger. Unknown work retains its reserved maximum; no paid provider is inferred.
- Adversarial regressions fixed dispatched-cancellation undercounts, swallowed fatal runner exceptions, null receipts becoming known costs, accidental lazy-provenance opt-in, lazy reference-image validation and dropped terminal cost cleanup.
- Local validation: **876 focused consumer tests + 62 compiler-package tests pass on each of net10.0/net8.0**. Compiler net10.0 coverage: **499/505 lines (98.81%), 331/360 branches (91.94%)**. Source/test DLL hashes matched. Scripted chats/execution test wiring; compilation is real. No live model or paid API call was made.
- Local packaging includes both TFMs, XML docs, license and README. Solution/release-pack registration and a dedicated source-pinned workflow are added. This does **not** prove compatibility with currently published AiDotNet/Evolution packages: Evolution 0.1.0-preview.1 predates the required APIs. A newer compatible release, dependency pin and package-path consumer check remain required.
- Program task v5, correctness gate v2 and I/O evaluator v2 reject older semantics. Automatic coordinated ledger/engine resume, multi-file evolution, correctness-driven repair, OS isolation and representative held-out performance/competitor confirmation remain unfinished. Current-head CI and independent review are pending; this stays draft.

See [C# contracts and limitations](https://github.com/ooples/AiDotNet/blob/feat/evolution-validated-promotion/docs/evolution-csharp.md) and the [full implementation tracker](https://github.com/ooples/AiDotNet.Evolution/blob/feat/competitive-evolution-platform/docs/IMPLEMENTATION_STATUS.md). Earlier validation below is historical, not a claim that every roadmap story is complete.

## Summary

Companion to ooples/AiDotNet.Evolution#15, implementing bounded US-03/05/17 slices and preserving evidence needed by US-18. The full roadmap remains in progress.

- Add AiModelBuilder.ConfigureProgramCorrectness with an internal CorrectnessGatedProgramFitnessEvaluator: trusted public correctness checks must report a maximization pass fraction of exactly 1 with zero constraint violations before fitness is evaluated.
- Reject positive fitness-stage constraint violations and account for both stages in the same cost units.
- Preserve Metrics and Artifacts when ProgramEvolutionTask merges descriptors. Previously enabling descriptors discarded runtime evidence and repair feedback.
- Bump program-evolution-task-v2 to v3 because retained repair artifacts can change the search trajectory; old checkpoints must not silently resume under new semantics.
- Correct a source-identity collision: hash exact source plus language, not whitespace-normalized display text; reject malformed Unicode, count actual source length, and use exact hashes in output schema v2. Task/variation/codec compatibility versions advance again for this semantic change. Cosmetic-only edits may now be evaluated separately.

## Given / When / Then

- Given an incorrect but fast program, when public correctness checks fail, then expensive fitness is not invoked and the result is not archive-admissible.
- Given a passing program, when checking and scoring finish, then costs include both stages and fitness evidence survives descriptor merging.
- Given null, failed, timed-out, infeasible or malformed pass-fraction results, when the gate processes them, then it fails closed.
- Given correctness checks configured through IAiModelBuilder, when BuildAsync starts program evolution, then failing checks prevent fitness execution and passing checks allow it without constructing an implementation helper.
- Given two multiline string literals differing in meaningful whitespace or line endings, when canonicalized, then they cannot share an evaluation identity. Given an exact duplicate with a new description, then its identity remains unchanged.

## Validation

Earlier v4 validation: all 1,042 selected tests passed separately on net10.0 and net8.0 (1,020 UnitTests.Evolution and 22 EvolutionFacadeIntegrationTests), including two additional malformed-source retry/accounting checks. Six regressions first failed against the old library; Roslyn independently verifies that the C# literal fixtures have different values. Explicit library and test-project builds completed before the final no-build test run. Whole-repository tests and hosted CI remain unvalidated.

Previously recorded scoped coverage passed the 1,040-test selection before the two additional retry tests: correctness decorator, genome codec and new Unicode validation method have 100% line/branch coverage; ProgramGenome has 98.24% line / 91.66% branch coverage. These are not whole-repository coverage figures. The previous ConfigureProgramCorrectness check also had 100% line/branch coverage; it was not included in this narrower collector. The subsequent net8.0 library and test-project builds succeeded, and 1,042 selected tests passed. Final net10/net8 builds disable diagnostic analyzers and use existing unchanged dependency assemblies; this is not full-repository/analyzer/net471 validation. The earlier compiler exit -1 has no established root cause.

Review follow-up: made the evaluator internal, added the fluent configuration method to AiModelBuilder and IAiModelBuilder, and updated the usage example. Current-head review approval remains pending; draft status is intentional.

## Integration and limits

The optional C# package now supplies syntax edits, real compiler emit and repair, but no OS sandbox or held-out-test exposure. Callers provide trusted checks and execution isolation. Shared accounting retains a reserved maximum when an evaluator throws or omits its receipt; this is conservative unknown consumption, not an exact measurement. Successful correctness metadata is not merged into fitness metadata.

The existing package migration #2092 was incorporated into this feature branch at f317ed04 and validated in db2094345. Neither master nor PR #2092 was merged/modified; copied engine sources/tests are removed rather than independently edited. See docs/evolution-package-integration.md for public API and checkpoint migration. Old identity-based checkpoints require a new run or explicit re-evaluation, not silent relabeling. A source hash alone does not fingerprint dependencies, compiler, hardware or test data. Full roadmap/US-03 is not claimed complete. See docs/evolution-correctness-gate.md, docs/evolution-source-identity.md and the core implementation tracker.

## Summary by CodeRabbit

* **New Features**
  * Added configurable correctness gates for program evolution.
  * Candidates must pass correctness checks before fitness evaluation; failed, cancelled, timed-out, or invalid checks are rejected.
  * Evaluation results preserve combined costs, diagnostics, metrics, and artifacts.

* **Changes**
  * Program identity and source hashing now use exact source text, including whitespace and line endings.
  * Source-size validation reflects the complete evaluated source.
  * Older checkpoints may be incompatible with the updated identity format.

* **Documentation**
  * Added guidance on gate behavior, evidence preservation, isolation, and compatibility.

Related Tensors companion: ooples/AiDotNet.Tensors#1024. Draft status is intentional; full roadmap completion and independent review are not claimed.

## Review follow-up and breaking changes

75aa6b1d0 addresses the current review findings: release documentation and PR notes explicitly identify ConfigureProgramCorrectness as a breaking addition to IAiModelBuilder. External implementations must implement it and recompile, forwarding/storing the gate or explicitly rejecting unsupported use; they must not silently bypass correctness checks. The correctness guide now names program-task v4. Malformed source is rejected via ParseFailed, bounded retry and parent fallback; it is not silently sanitized. Variation compatibility advances to v4-source-validation-retries because the retry trajectory changes. Review approval and hosted CI remain pending.

## Protected-source and compatibility follow-up

Revision ddd80160b fixes ten demonstrated pre-v5 regressions: protected code could change in a full rewrite, and nine proposal settings did not alter checkpoint compatibility. Variation v5 fingerprints the additional options and separately encodes feature names/marker pairs. All proposal formats must preserve exact protected characters and marker structure. The executable fence path now preserves mixed line endings and source whitespace; it requires a closing fence and treats its single delimiter newline as transport (an extra blank line retains a source EOF newline). Public display extraction remains unchanged.

Given an out-of-region rewrite, when it is parsed, then bounded ParseFailed feedback rejects it. Given valid multi-block edits or CRLF diffs, when applied, then protected text remains exact. Given a changed proposal setting, when constructing an operator, then old checkpoints cannot silently reuse the prior compatibility hash.

Final v5 local validation: 1,082 authored Evolution/facade tests passed separately on net10.0 and net8.0, including 40 new cases. A local focused harness compiled the existing test sources against the actual built library; production/test-copy DLL SHA-256 matched. The new boundary helper has 100% line/branch coverage and fenced extraction 99.1% line/92.72% branch on net10. These are scoped results; diagnostic analyzers were disabled and whole-repository/net471/hosted validation remains outstanding. Formatting and git diff --check passed. This is still partial roadmap implementation, not compiler-guided editing or a claim of competitive superiority. Current-head hosted checks and independent approval must be re-established.

## Standalone dependency integration

Incorporates #2092 at 104a2a41a47ebc8143cac230069462f8c14c08c3 through a non-conflicting feature-branch merge, retaining exact-source and protected-edit fixes. This enables subsequent compiler/model proposals to reuse the standalone resource ledger rather than duplicate billing. No PR was merged into master.

Validation at db2094345: 857 selected consumer tests passed separately on net10.0 and net8.0 against core 6d9aeb2, including real MAP-Elites AutoML, facade and YAML integration. The count is lower because the migration removes duplicated generic core tests. One assertion was updated to require the exact engine-owned parent snapshot (distinct from caller input, identical source and identity) on repair exhaustion. Main libraries built explicitly, actual production/test-copy DLL hashes matched, and diagnostic analyzers were disabled. Whole-repository/net471/hosted/package-path validation and current-head approval remain outstanding.

Publication correction: NuGet currently provides 0.1.0-preview.1, whose nuspec points to f0f282cf; #2092's old awaiting-publication note is stale. That artifact predates new roadmap APIs and cannot substitute for a newer core release. External consumers must update generic-engine namespaces/assembly references and recompile; migrated ConfigureEvolution signatures also change binary/interface contracts. The migration guide records exact dependency and assembly evidence.

### CODE REVIEW

File: src/Evolution/Programs/CorrectnessGatedProgramFitnessEvaluator.cs [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+/// <summary>Runs explicit correctness checks before an expensive program fitness evaluation.</summary>
+/// <remarks>
+/// The correctness evaluator must report a maximization score: the fraction of required public checks passed,
+/// with 1 meaning all passed. A completed score below 1 or any positive constraint violation rejects the program.
+/// Use deterministic tests or trusted reference comparisons, not an LLM judge, for this gate. Both evaluators
+/// remain responsible for sandboxing, timeouts and truthful cost reporting in the same units. This wrapper
+/// neither executes code itself nor provides an isolation boundary. Final held-out validation belongs outside
+/// the search: its cases and diagnostics must not be fed into proposal generation.
+/// </remarks>
+public sealed class CorrectnessGatedProgramFitnessEvaluator : IProgramFitnessEvaluator
```
[the remark this answers is not in the document]
Comment (ooples) [reply src/Evolution/Programs/CorrectnessGatedProgramFitnessEvaluator.cs]: Addressed in 46046925d. CorrectnessGatedProgramFitnessEvaluator is now internal; AiModelBuilder and IAiModelBuilder expose ConfigureProgramCorrectness, and program-run assembly applies the gate before the configured fitness evaluator. The documentation now uses the fluent facade.

Validation: 1,028 selected tests passed on net10.0 (1,006 UnitTests.Evolution and 22 EvolutionFacadeIntegrationTests), including new facade cases for rejected checks, passing checks and null configuration. git diff --check passed. Hosted CI and current-head review approval remain pending; the PR is still a draft.

File: src/Interfaces/IAiModelBuilder.cs [hunk 2]
```diff
@@ -2699,6 +2699,13 @@ IAiModelBuilder<T, TInput, TOutput> ConfigureEvolution<TGenome>(
     /// </remarks>
     IAiModelBuilder<T, TInput, TOutput> ConfigureProgramEvolution(ProgramEvolutionOptions options);
 
+    /// <summary>Requires trusted public correctness checks before evaluating program fitness.</summary>
+    /// <param name="correctness">Checks reporting a maximization pass fraction in [0, 1]. Only exactly 1 and
+    /// zero constraint violations pass. The caller owns isolation and versioning; never expose held-out tests.</param>
+    /// <returns>This builder for fluent configuration.</returns>
+    /// <remarks>Pair with ConfigureProgramEvolution. Checking and fitness costs must use the same units.</remarks>
+    IAiModelBuilder<T, TInput, TOutput> ConfigureProgramCorrectness(IProgramFitnessEvaluator correctness);
```
[the remark this answers is not in the document]
Comment (ooples) [reply src/Interfaces/IAiModelBuilder.cs:2716]: Addressed in 75aa6b1d0. CHANGELOG.md and docs/evolution-correctness-gate.md now explicitly document the breaking IAiModelBuilder member, required external implementation/recompilation, and safe unsupported behavior. The guide also names task v4. The outside-diff malformed-source finding is fixed through ParseFailed and bounded retry, with variation v4 compatibility. Final validation: 1,042 selected tests pass separately on net10.0 and net8.0; builds disabled diagnostic analyzers. Hosted checks/current-head approval remain pending.

**Comment by ooples** [comment]
Closing this. The work is real but it is in the wrong repository, and it cannot build here for a structural reason rather than a fixable one.

## Why it cannot build

`Build & Validate` fails with `error CS0246` on seven types referenced by `src/Evolution/Programs/PersistentProgramFitnessEvaluator.cs` and `src/Configuration/ProgramEvolutionResourceOptions.cs`:

`EvolutionReuseScope`, `EvolutionEvaluationReusePolicy`, `EvolutionEvaluationCacheKey`, `EvolutionPersistentEvaluationCache`, `IEvolutionEvaluationStore`, `EvolutionResourceLedger`, `EvolutionResources`

None of them exists anywhere. Not on `master`, not defined on this branch, and not in AiDotNet.Evolution. The PR body notes that "the published core preview lacks these APIs", but the sharper fact is that they were never written: this branch consumes an engine surface that does not exist, so no amount of rebasing or wiring here makes it green.

## Why it belongs in AiDotNet.Evolution

Per that repo's README, it is a task-agnostic quality-diversity engine, and program evolution is explicitly named as a *domain integration* that supplies genomes, validation, variation and evaluation through the public contracts. The three missing concepts — evaluation reuse scope, an evaluation store boundary, and a resource ledger that keeps unknown work at its reserved maximum — are engine concerns, not C#/Roslyn concerns. They are about caching and cost accounting and mention nothing about programs.

Filed as **ooples/AiDotNet.Evolution#107**, with each type's requirements read off the call sites on this branch rather than guessed.

## Nothing is lost

The branch `feat/evolution-validated-promotion` is not deleted; closing the PR leaves it intact at `8c8a90b2f7`. Two things worth recording about its contents:

**Unique to this branch** — the program-evolution work to port once the engine API lands:

- `src/AiDotNet.Evolution.CSharp/` — `CSharpPatchCompiler`, `CSharpProposalSource`, options and extensions
- `src/Evolution/Programs/` — `CorrectnessGatedProgramFitnessEvaluator`, `PersistentProgramFitnessEvaluator`, `VersionPinnedProgramFitnessEvaluator`, `ProgramEditBoundary`, `IProgramVariationOperator`
- `tools/AiDotNet.CSharp.Worker/` — the offline compile-only worker
- `tools/AiDotNet.Evolve.Cli/ProgramBenchmark.cs` — `benchmark-program`
- six `docs/evolution-*.md` guides and the matching test projects

**Not unique, and not a reason to keep this open** — the branch also carries #2090 options-surface files (`ModelHyperparameterOptions`, `EmbeddingModelOptions`, `GanOptions`, `VideoHyperparameterOptions` and the design spec). Those are absent from `master` but present on `feature/options-surface-phase-7-audio`, so closing this discards no options work.

One consequence to be aware of: this branch bundled two unrelated efforts, which is part of why it grew to 185 commits and 384 modified files and never converged. The port should keep the engine API, the domain integration and the options surface as separate changes.
