### ISSUE TITLE
[Epic] Model-family invariants drive one entry path per model (plus: the coverage report is broken, and 345 models have no test class)

### ISSUE THREAD

**Issue by ooples** [ooples/AiDotNet#2091]
## Summary

The automated test scaffold is believed to give every model full invariant coverage. It does not: measured on master `a22d7e78bf`, roughly **1170 of 1816 annotated models (~64%) have no model-family test running against them at all**.

The reason nobody knew is the second half of this issue: the generator's own coverage report is **structurally incapable of measuring coverage**, and has been reporting `0.1%` — a number so obviously wrong that it reads as noise rather than signal.

These belong together because they share one root cause: the gap was invisible.

## Part 1 — the coverage report cannot measure coverage

`src/Generated/.../TestScaffoldGenerator/TestCoverage.g.cs` currently emits:

```csharp
public const int TotalModels = 1816;
public const int TestedCount = 2;
public const int UntestedCount = 1814;
public const double CoveragePercent = 0.1;

public static IReadOnlyList<string> TestedModelNames { get; } = new string[]
{
    "NeuralStressTest",
    "TEST",
};
```

`HasTestCoverage(modelClassName, testNames)` (`TestScaffoldGenerator.cs:15525`) checks whether a class named `<Model>Tests` / `<Model>IntegrationTests` / `<Model>UnitTests` exists **in the same compilation**. But this file is generated into the **`AiDotNet` (src) assembly**, where there are no test classes at all — the tests live in `AiDotNetTests`.

So the check can only ever match models whose own names happen to end in `Test`. That is exactly what the two "covered" entries are: `NeuralStressTest` and `TEST` are *models*, self-matching on their own names.

The result is wrong in **both** directions:
- It cannot see the ~609 models that genuinely are covered.
- It reports 0.1%, which is so far from plausible that it was never actionable.

## Part 2 — the real gap is ~1170 models

Measured by whole-word type-name reference across the entire `tests/AiDotNet.Tests/ModelFamilyTests/` corpus:

| | Count |
|---|---:|
| Annotated models tracked by the generator | **1816** |
| Flagged untested by the generator | 1779 |
| …genuinely **not referenced anywhere** in ModelFamilyTests | **1170** |
| …actually referenced, so covered | 609 |
| ModelFamilyTests `.cs` files | 590 |

Real model-family coverage is therefore about **646 / 1816 ≈ 36%**.

**Instrument caveat, stated up front:** this counts whole-word type-name references, so a model reached only via a factory or a registry string would be scored as uncovered. 36% is a floor rather than an exact figure. A filename-based count (`<Name>Tests.cs`) gave 1268 missing — 98 worse — which is why the reference-based number is the one quoted here. The exact figure should be re-derived once Part 1 gives a trustworthy instrument.

Sample of genuinely-unreferenced models: `A2CAgent`, `A3CAgent`, `ABCNet`, `ABINet`, `ABME`, `ABODDetector`, `ACLAlgorithm`, `AMT`, `ANILAlgorithm`, `ANPAlgorithm`, `APNet2`, `ARIMADetector`, `AST`, `ASTModel`, `ATAMLAlgorithm`, `AVHuBERT`, `AVID`, `AcousticToxicityDetector`, `GaussianSplatting`, …

## What this let through — a worked example

#2089 is the concrete cost. `GaussianSplatting` densification (`EnableDensification` defaults to **true**) desynchronised `ParameterCount` from the live Gaussian cloud, so training crashed on the step after the first split:

```
System.ArgumentException : Flat gradient length (224) must match ParameterCount (112).
```

A default-on feature in a shipped model broke training outright, and CI stayed green — because `GaussianSplatting` is one of the 1170. The generated invariants (gradcheck, training-reduces-loss, clone, serialize round-trip, parameter-count contract) never ran against it.

The hand-written tests that did exist all avoided the failing combination: the densification tests drive the internal `RunDensifyAndPruneForTest` hook rather than the training loop, and the image-space training test sets `EnableDensification = false`. That is the pattern a generated invariant suite exists to defeat.

## Proposed scope

**Phase 1 — make the number true (small, do first).**
- Emit the coverage report from the `AiDotNetTests` compilation, where test classes are actually visible, or have the generator consume the test assembly's symbols.
- Fix the self-match: a model named `*Test` must not count as its own coverage.
- Publish the true baseline.

**Phase 2 — make the number a gate.**
- Fail the build (or a dedicated CI lane) when coverage regresses below the recorded baseline, so the gap cannot silently widen again — mirroring how the analyzer gates the parameter surface.

**Phase 3 — close the gap.**
- Determine why the scaffold generator skips ~1170 models (unsupported constructor shapes? missing fixture geometry? opt-out attributes?) and emit invariants for them.
- Expect this to surface a substantial number of real failures; #2089 suggests the yield will be high.

Phase 3 is the large one and should be scheduled as its own PR.

## Acceptance

- [ ] `TestCoverage.g.cs` reports a figure that matches an independent count of the test corpus
- [ ] A model named `*Test` no longer counts as covering itself
- [ ] The true baseline is recorded and gated against regression
- [ ] `GaussianSplatting` (and the rest of the 1170) run the model-family invariants

---

*Filed from the full re-audit of all 45 open issues against master on 2026-09-05. Related: #2089 (the crash this gap allowed), #1872 (the gradcheck invariant that would have run had the model been covered).*

**Comment by ooples** [comment]
## Correction — the 36% figure in this issue is wrong. Real coverage is ~81%.

I filed this using a **file-based count** of `tests/AiDotNet.Tests/ModelFamilyTests/`. That instrument cannot see the model-family tests, because they are **generated into the compilation by `TestScaffoldGenerator` and never written to disk** (`EmitCompilerGeneratedFiles` is off for the test project, so `obj/` contains only `GlobalUsings.g.cs`). Counting checked-in files therefore missed essentially the entire generated suite.

Re-measured by enumerating the actual test assembly (`dotnet test --list-tests`):

| | Count |
|---|---:|
| Total test ids in the assembly | **78,479** |
| Distinct test classes | **3,506** |
| Models tracked by the generator | 1816 (name list has 1781) |
| Models **with** a `<Name>Tests` class | **1,436** |
| Models **without** | **345** |
| **Coverage** | **~80.6%** |

**`GaussianSplattingTests` does exist** — 30 generated invariants, including `Training_ShouldReduceLoss`, `ParameterCount_ShouldMatchGetParameters`, `Parameters_CountShouldMatchVector_AfterForward`, `Clone_AfterTraining_ShouldPreserveLearnedWeights`. My original claim that it had zero coverage was simply false.

## So why did #2089 escape a covered model?

Not coverage breadth — **entry-path depth**. The scaffold drives exactly one canonical path per model, and for `GaussianSplatting` that is **ray-mode** training (`TestScaffoldGenerator.cs:12221`):

```csharp
sb.AppendLine("    protected override int[] InputShape => new[] { 4, 6 };");
sb.AppendLine("    protected override int[] OutputShape => new[] { 4, 4 };");
```

with the note that "the model now accepts ray-mode training too … so the scaffold can use one shape for both calls."

But densification only runs in **camera-mode** training. `GaussianSplatting.cs` states it outright: *"Route through GS's paper-faithful CAMERA-mode Train — that's the path that runs the #1835 densification loop … RAY-mode training bypasses densification by design."*

So `ParameterCount_ShouldMatchGetParameters` exists and passes, but never observes a densified cloud, because the only path the scaffold drives is the one where densification cannot fire. A default-on feature was invisible to a covered model.

## Revised scope of this issue

**Part 1 — the coverage report is still broken (unchanged, still valid).** `TestCoverage.g.cs` reports `TestedCount = 2`, `CoveragePercent = 0.1`, with `TestedModelNames = { "NeuralStressTest", "TEST" }` — two *models* whose names end in `Test`, self-matching. `HasTestCoverage` compares against test classes in the **same compilation**, but the report is emitted into the `AiDotNet` src assembly where none exist. It is wrong by ~800x, which is exactly why the real number was never known — including by me when filing this.

**Part 2 — 345 models still have no `<Name>Tests` class.** Real, but a quarter the size I claimed. Sample: `ACGAN`, `ACLAlgorithm`, `ANILAlgorithm`, `ANPAlgorithm`, `APNet`, `ATAMLAlgorithm`, `AcousticToxicityDetector`, `AdaptedMetaModel`, `AmazonPolly`, `AnoGANDetector`, `AquilaVL`, `Aria`, `AsymmDiTPredictor`.

**Part 3 (new, and the one that actually matters) — single-entry-path invariants.** The scaffold exercises one canonical path per model. Alternate training modes and default-on feature flags (densification being the worked example) are unexercised, so a model can be fully "covered" and still ship a crash on its default configuration. This is the gap that produced #2089, and it would not be closed by raising coverage from 81% to 100%.

## Lesson worth keeping

The instrument disagreed with reality by 2x in one direction (81% vs my 36%) and ~800x in the other (the generator's own 0.1%). Any future coverage number here should be derived from `--list-tests` against the built assembly, never from the file tree and never from `TestCoverage.g.cs` until Part 1 is fixed.

**Comment by ooples** [comment]
## Another instance: paper-scale training recipes cannot run on test-scale fixtures

Surfaced while implementing #1928's recipe factory, and it belongs here rather than there because it is the same shape as this epic's existing finding — the generated fixtures do not represent the configuration the library actually ships.

When models were made to train with the optimizer, learning rate and schedule their papers specify, two of the first eleven stopped passing their model-family tests. Neither value is wrong; both are what the paper says, and this is the first time the library has run them.

**A 4000-step warmup inside a 100-step fixture.** `AttentionNetwork` (Vaswani et al., Sec. 5.3) warms up over 4000 steps. The generated fixture runs on the order of a hundred, so the learning rate stays near zero for the entire run and parameters never move — `Training_ShouldChangeParameters` and `GradientFlow_ShouldBeNonZeroAndFinite` both fail. Isolated by removing only the schedule line, which made all three failures disappear.

**A rate tuned for batch 4096 applied at batch 32.** `MobileNetV3` (Howard et al., Sec. 6.1) uses RMSProp at 0.1 on a 4x4 TPU pod. Control run: the model passes 29/30 with no recipe and fails 3 with it. Scaling the rate to the fixture's batch by the linear scaling rule (Goyal et al. 2017) did **not** fix it and made a fourth test fail, so rate magnitude is not the whole story — either the fixture cannot represent this recipe or the RMSProp implementation has a problem.

### Partial mitigation already in #1928

The factory now rescales warmup to the share of the run it occupies in the paper, floored at one step — the same move #1835 makes for GaussianSplatting's densification window, which would otherwise never fire because its start iteration exceeded the configured run. A full-length run still gets the paper's number unchanged. The recipe attribute also gained `ReferenceBatchSize` so rates stated for large batches can be scaled rather than transplanted.

That is enough for warmup. It is not enough in general, and the two models above are held back undeclared rather than tuned until green.

### Why this belongs to this epic

The underlying question is the same one the single-entry-path finding raises: **what configuration should a generated fixture exercise?** If it runs library defaults, it does not test what users get. If it runs the paper recipe, it needs to represent that recipe's scale — hundreds of steps and realistic batch sizes — or it reports failures that say more about the fixture than the model.

Resolving it is a prerequisite for populating the remaining ~548 recipes, because every recipe carrying a warmup, a large-batch rate, or a long decay schedule will hit the same wall.

**Comment by ooples** [comment]
## Phase 1 is done, and it changes the scope of Phases 2 and 3

Branch: `fix/2091-coverage-instrument` (commit `2e05cd54ff`).

**Part 1 reproduced and fixed. Part 2 does not survive checking — real coverage is ~80.7%, not ~36%.** Details and evidence below, including two of my own instruments that were wrong before they were right.

---

## Part 1 — confirmed, with a correction to the mechanism

The diagnosis is right: the report was emitted from the `AiDotNet` compilation, where no test class exists, because a source generator's syntax provider observes only the compilation it runs in.

The *mechanism* differs from this issue's account, though. The issue says `NeuralStressTest` and `TEST` are "models, self-matching on their own names". That is true of the first and not the second:

- `NeuralStressTest` ends in `Test`, so `IsTestCandidate` admits it to `testNames`, and it then matches **itself** in the word-boundary loop.
- `TEST` **never enters `testNames` at all** — `IsTestCandidate` uses an ordinal `EndsWith("Test")`, and `"TEST"` does not end in `"Test"`. It was scored covered because the loop found `"TEST"` case-insensitively at the *tail of `NeuralStressTest`* (index 12 of 16) and accepted the empty remainder via `if (afterMatch >= testName.Length) return true;`. **An unrelated model's name vouched for it.**

Verified by porting `IsTestCandidate` + `HasTestCoverage` to a standalone harness:

```
models admitted into testNames by IsTestCandidate: ['NeuralStressTest']
  NeuralStressTest   -> wordloop:empty-remainder vs 'NeuralStressTest'
  TEST               -> wordloop:empty-remainder vs 'NeuralStressTest'
```

This matters for the fix: rejecting exact self-equality alone would have left `TEST` covered. Both paths are now closed — a candidate equal to the model is skipped, and an empty remainder no longer counts; a recognised test suffix is required.

**Minor correction to the framing:** `src/Generated/` is in `.gitignore` (line 45), so `TestCoverage.g.cs` is a local build artifact, not a checked-in file. It is still the artifact a developer would look at, so the substance stands.

### What the fix does

The report is now published only from the compilation that can measure it. This is not merely unimplemented in the source compilation — it is **impossible** there: `AiDotNetTests` references `AiDotNet` and never the reverse, so the source compilation cannot consume the test assembly's symbols. The issue's suggested alternative ("or have the generator consume the test assembly's symbols") is not achievable.

`AiDotNet` now emits `IsMeasurable = false` with `-1` sentinels, keeping `TotalModels` (which is real — the census needs no test classes). Emitting `0` would have read as "nothing is covered", which is a different lie.

The flag keys on `isTestProject`, not `!modelsFoundFromSource`: the latter is also false for any project that simply declares no models, so a future non-test project referencing `AiDotNet` would have started publishing a fabricated 0%.

Three regression tests drive the generator over synthetic compilations and pin both behaviours. **All three fail with the change reverted** (verified in both directions).

---

## Part 2 — the ~1170 figure is an artifact of the measurement

**The generator reports 1466 of 1816 models covered (80.7%).**

The `~36%` figure counts whole-word type-name references across `tests/AiDotNet.Tests/ModelFamilyTests/`. But **1,300 model-family test classes are source-generated and exist only at compile time** — they are never files under `tests/`. A reference count over that directory cannot see them.

I reproduced the issue's number exactly using the hand-written corpus alone, then re-ran the same instrument with the generated classes included:

| Corpus | Covered | Coverage |
|---|---:|---:|
| Hand-written `ModelFamilyTests/*.cs` only (**this issue's method**) | 626 | **34.5%** |
| Hand-written **+ generated test classes** | 1443 | **79.5%** |
| Generator's own report (`TestCoverage.g.cs`, test compilation) | 1466 | **80.7%** |

The independent count and the generator agree to within 1.2 points, with **zero** cases where the generator claims coverage the independent count cannot corroborate (1423 mutual, 33 disagreements each way — the residue expected between name-reference and symbol-based matching).

### The worked example refutes it directly

`GaussianSplatting` — the model whose supposed uncovered-ness let #2089 ship — **has a generated test class and passes 29 of 30 invariants**:

```
Passed!  - Failed: 0, Passed: 29, Skipped: 1, Total: 30
  filter: FullyQualifiedName~ModelFamilyTests.Generated.GaussianSplattingTests
```

Its generated scaffold inherits `NeuralNetworkModelTestBase<float>` and constructs the model with its defaults, i.e. with `EnableDensification = true`. `ABINet`, also on the issue's "genuinely unreferenced" sample list, likewise has a generated class.

Of the 1,300 generated files: **1,295 inherit a real invariant test base, 0 are runtime-throwing stubs, 1 carries a `Skip`.** The coverage is not vacuous.

I have not established *when* `GaussianSplatting` gained its scaffold, so I cannot rule out that coverage improved between `a22d7e78bf` and today. But the measurement flaw is independent of that and is sufficient on its own to explain the gap between 36% and 80.7%.

### Two of my own instruments were wrong first

Stating these because they are the same class of error this issue is about:

1. My first cross-check walked `TestCoverage.g.cs` itself, whose string literals name **every** model — inflating coverage to 98.1%. Excluding the report being checked gives 79.5%.
2. My first census read the `ModelStateGenerator` state files, which include optimizers and mangle generic arity — a 1541-model population, not the generator's 1816.

Neither number should have been trusted, and neither is quoted above.

---

## The control arm is the most important result

**The test-side figure is 1466 both with and without my fix.**

```
CONTROL (master generator):  TestedCount = 1466   CoveragePercent = 80.7
FIXED   (this branch):       TestedCount = 1466   CoveragePercent = 80.7
```

So the correct number **already existed on master** — published by the `AiDotNetTests` compilation and by the `AIDN041` diagnostic, which reports `1466 of 1816 annotated models have test coverage (80.7%)`. It was simply invisible, one warning among thousands, while the artifact a developer would open said 0.1%.

The bug was never that no correct number existed. It was that **two** numbers existed, and the wrong one was the visible one.

---

## Proposed rescope

- **Phase 1** — done, as above.
- **Phase 2 (gate it)** — still worth doing and now cheap: there is a trustworthy number and an existing `AIDN041` diagnostic to read. Baseline at **1466 / 1816** and fail on regression. Proceeding with this.
- **Phase 3** — **mis-scoped as written.** The gap is **350 models, not ~1170**, and its character is different: these are largely models the scaffold *cannot construct*, which `AIDN040` already names one by one ("could not be auto-generated (missing category/task metadata)"), rather than models nobody thought to test. Worth re-filing against the real 350 before anyone estimates it.

The acceptance criterion "reports a figure that matches an independent count of the test corpus" is met: 80.7% vs 79.5%.

**Comment by ooples** [comment]
## Phase 2 done. Phase 3 is now properly diagnosed — and it is not a metadata problem.

Branch `fix/2091-coverage-instrument`, commit `b1e033e0fe`.

---

## Phase 2 — the number is a gate

`ModelCoverageBaselineTests` holds the measured figure to **1466 of 1816** with four assertions:

1. the test compilation still publishes a **measured** figure (`IsMeasurable`), so the Phase 1 defect cannot reappear from the other side;
2. the tested count has not fallen;
3. **the census has not shrunk** — models losing their metadata attributes drop out of the denominator entirely, which would otherwise let coverage "improve" by shrinking it;
4. the report is internally consistent.

The report is read by **reflection** rather than by naming the type. `AiDotNet` sets `InternalsVisibleTo("AiDotNetTests")` and the generator emits `TestCoverage` into *both* compilations, so `AiDotNet.Generated.TestCoverage` is in scope twice in the test assembly. A direct reference binds to this assembly's copy silently and warns (CS0436). That collision is also the likeliest reason the report had **zero consumers** in the entire repository.

Verified in both directions, because a gate that only ever passes is not a gate:

- baseline raised to 1467 → `Model-family coverage fell from 1467 to 1466 of 1816 models`
- Phase 1 generator change reverted → all four fail with `TestCoverage.IsMeasurable is missing`

So the gate is coupled to the fix rather than passing on its own.

---

## Phase 3 — the cause is already diagnosed, by a different diagnostic

This issue proposes Phase 3 as *"Determine why the scaffold generator skips ~1170 models (unsupported constructor shapes? missing fixture geometry? opt-out attributes?)"*.

**The generator already determines this and already reports it.** Every one of the 338 uncovered models emits `AIDN040`, and **325 of them additionally emit `ADNGEN001`, which names the specific reason:**

| Models | Reason (`ADNGEN001`) |
|---:|---|
| **224** | inherits from a base excluded from generation (compositional or wrapper pattern) |
| **55** | no supported parameterless, architecture-only, or vector-only constructor |
| **21** | resolves to test family `NeuralNetwork`, whose fixture requires an interface the type does not implement |
| **17** | resolves to test family `Diffusion`, same shape |
| **6** | resolves to test family `TimeSeries`, same shape |
| **2** | resolves to test family `GAN`, same shape |
| *13* | *no `ADNGEN001` — these are the genuinely metadata-less ones* |

### AIDN040 has been misattributing the cause

Its message reads `could not be auto-generated (missing category/task metadata)`. That is wrong for 325 of the 338. `ACLAlgorithm`, `ANILAlgorithm` and `ANPAlgorithm` — all on this issue's "genuinely unreferenced" sample list — each carry `[ModelDomain]`, `[ModelCategory]` **and** `[ModelTask]`:

```csharp
[ModelDomain(ModelDomain.MachineLearning)]
[ModelCategory(ModelCategory.MetaLearning)]
[ModelCategory(ModelCategory.NeuralNetwork)]
[ModelTask(ModelTask.Classification)]
```

They are skipped because they inherit an excluded compositional base, not because they lack metadata. Naming the wrong cause on every one of 338 warning lines is worse than naming none: it sends the reader to fix something that is not broken. Fixed on this branch — `AIDN040` now points at the model's `ADNGEN001` and reserves the metadata claim for the 13 cases where it is actually true.

### What Phase 3 actually is

Four separable pieces, in descending order of tractability:

1. **46 family-interface mismatches** (NeuralNetwork 21, Diffusion 17, TimeSeries 6, GAN 2). A model resolving to a family whose fixture it cannot satisfy is either a wrong family mapping or a model genuinely missing an interface it ought to implement. **Most likely to surface real defects, smallest to attempt.**
2. **13 genuinely metadata-less models** — mechanical, add the attributes.
3. **55 unsupported constructor shapes** — needs either new constructor support in the scaffold or manual fixtures.
4. **224 excluded-base models** — a deliberate design decision (compositional and wrapper patterns cannot be auto-constructed). Changing it is the architectural piece, and it is the bulk. This is where a re-file is warranted rather than an estimate.

Note that #2089 sits in **none** of these buckets: `GaussianSplatting` is covered and passing, per my previous comment.

---

## Acceptance criteria

- [x] `TestCoverage.g.cs` reports a figure that matches an independent count of the test corpus — 80.7% vs 79.5%
- [x] A model named `*Test` no longer counts as covering itself — and neither does an unrelated model whose name it happens to end with
- [x] The true baseline is recorded and gated against regression — 1466/1816, both directions verified
- [ ] `GaussianSplatting` (and the rest of the 1170) run the model-family invariants — **`GaussianSplatting` already did** (29/30 passing); the remaining set is 338, broken down above

I'd suggest re-titling this issue and re-filing bucket 4 separately, since "~1170 models have no test" is the premise most likely to be quoted downstream.

**Comment by ooples** [comment]
## Correction to my previous comment, and the last Phase 3 fix

Commit `2cf2d22051`.

### Retracting the "13 genuinely metadata-less models"

My previous comment's breakdown table ended with *"13 — no `ADNGEN001`, these are the genuinely metadata-less ones"*. **That is wrong. All 13 carry `[ModelCategory]` and `[ModelTask]`.**

I then went further wrong. Chasing those 13, I found they appear in **both** `TestedModelNames` and `UntestedModelNames`, and that `LayoutLMv3` runs 37 tests while the report called it uncovered. I concluded the report was double-counting, and wrote a fix.

**There was no double-count.** The 13 are 13 pairs of *different classes sharing a simple name across namespaces*:

| Name | Covered | Not covered |
|---|---|---|
| `LayoutLMv3` | `Document.LayoutAware` | `VisionLanguage.Document` |
| `Nougat` | `Document.PixelToSequence` | `VisionLanguage.Document` |
| `WaveNet` | `Finance.Forecasting.Neural` | `TextToSpeech.Vocoders` |
| `AudioLM` | `Audio.Generation` | `TextToSpeech.CodecBased` |

…and likewise `AudioPaLM`, `Branchformer`, `EBranchformer`, `FishSpeech`, `GLaMM`, `GroundedSAM2`, `Pix2Struct`, `VALLE`, `VoiceCraft`.

So `1466 + 350 = 1816` was correct throughout, `AIDN040` firing on `LayoutLMv3` was always right (it meant the VisionLanguage one), and my `--filter FullyQualifiedName~LayoutLMv3` measurement was matching the *other* class. The fix I wrote was a no-op; building it and seeing the overlap unchanged at 13 is what caught it. Reverted.

### The real defect that caused it — fixed

`ADNGEN001` names models fully qualified (`global::AiDotNet.AnomalyDetection.NeuralNetwork.AnoGANDetector<T>`). `AIDN040` and the coverage report named them by **simple name**. The two diagnostics therefore could not be cross-referenced, and neither could be checked by hand — a reader seeing `Model 'LayoutLMv3' has no test` cannot tell which class is meant or find its `ADNGEN001` line.

Both now emit fully-qualified names. The effect is measurable and is itself the proof that no double-count existed:

| | Before | After |
|---|---:|---:|
| Names in **both** lists | 13 | **0** |
| Repeated names within untested | 12 | **0** |
| `TestedCount` / `UntestedCount` / `TotalModels` | 1466 / 350 / 1816 | **1466 / 350 / 1816** |

The totals not moving is the point: the apparent overlap was ambiguity in the *labels*, not error in the counts.

### Corrected Phase 3 breakdown

| Models | Reason (`ADNGEN001`) |
|---:|---|
| 224 | inherits a base excluded from generation (compositional/wrapper) |
| 55 | no supported parameterless, architecture-only or vector-only constructor |
| 21 | family `NeuralNetwork` — fixture requires `INeuralNetworkModel`, not implemented |
| 17 | family `Diffusion` — same shape |
| 6 | family `TimeSeries` — same shape |
| 2 | family `GAN` — same shape |
| 13 | **the name-collision pairs above — not metadata-less; each is a second class that simply has no fixture** |

Also worth noting against this issue's sample list of "genuinely unreferenced" models: `A2CAgent` and `A3CAgent` both appear in `TestedModelNames`.

### Where Phase 3 stands

Phases 1 and 2 are complete and gated. Phase 3's *diagnosis* is complete — every uncovered model now has an unambiguous, individually-named reason — but the *remediation* is four separate pieces, and the largest (224 excluded-base models) is an architectural decision about whether compositional and wrapper patterns should be auto-constructible at all. That deserves its own issue rather than an estimate here.

The 46 family-interface mismatches remain the most promising place to find real defects: `ConstantQTransform` and the RL policy types look mis-categorised into the `NeuralNetwork` family, while `FasterRCNN` and `YOLOv9` look like they genuinely should implement `INeuralNetworkModel`.

**Comment by ooples** [comment]
## Phase 3: the generator-side work is done, and the family bucket splits cleanly in two

Commit `cac501215b`. Draft PR: #2136.

### A real routing bug — 11 models

`ResolveTestBaseClass` priority 18 read:

```csharp
if (model.ImplementsNeuralNetworkModel || model.UsesTensorInput)
    return TestFamily.NeuralNetwork;
```

But `IsCompatibleWithFamily(NeuralNetwork)` **is** `ImplementsNeuralNetworkModel`. So a type reaching that line only via `UsesTensorInput` was assigned a family it could not satisfy *by construction* — an `ADNGEN001` that no change to the model could ever clear. Tensor input is not evidence of being a neural network.

Eleven models were mis-routed: `ConstantQTransform` (a signal transform declaring `[ModelCategory(SignalProcessing)]`) and the entire `Safety.Image` / `Safety.Video` / `Safety.Multimodal` cluster of classifiers, deepfake detectors and moderators. They now report that no family could be resolved — which is true — instead of a neural-network failure, which was not.

This cannot remove coverage: emitting a fixture already required `IsCompatibleWithFamily`, hence the interface, hence the surviving condition. **`TestedCount` is 1466 before and after**, which the Phase 2 gate asserts on every run.

### A diagnostic regression the same change introduced, caught by comparing the whole distribution

Family resolution ran *before* the excluded-base check. Once priority 18 stopped catching them, **30 compositional models that also resolve to no family** started reporting the vaguer "no test family could be resolved" instead of "inherits from a base excluded from generation" — trading a specific, actionable reason for a generic one.

Checking the target number alone would not have shown this. Only the full before/after reason mix did:

| Reason | orig | priority-18 only | final |
|---|---:|---:|---:|
| inherits excluded base | 224 | 194 | **224** |
| no supported constructor | 55 | 54 | 54 |
| family `Diffusion`, interface missing | 17 | 17 | 17 |
| **no test family could be resolved** | 0 | 42 | **12** |
| family `NeuralNetwork`, interface missing | 21 | 10 | **10** |
| family `TimeSeries`, interface missing | 6 | 6 | 6 |
| family `GAN`, interface missing | 2 | 2 | 2 |

The excluded-base check now runs first: an excluded base means no fixture whatever the family, so it is strictly the more specific reason.

### The remaining 35 are model defects, not generator defects

After the routing fix, every remaining family mismatch has the same shape: **the model explicitly declares a category and does not implement that family's interface.** The family assignment reflects the author's own declaration, so it is right, and the missing interface is the finding.

- `YOLOv9` — `[ModelCategory(NeuralNetwork)]`, extends `ObjectDetectorBase`, no `INeuralNetworkModel`
- `MatchaTTS` — `[ModelCategory(Diffusion)]`, extends `AudioNeuralNetworkBase`, no `IDiffusionModel`
- `FasterRCNN`, the GARCH family, `AnoGANDetector` / `GANomalyDetector`, and the rest follow the same pattern

`ADNGEN001` already names each one individually and states exactly which interface is absent, so nothing further is needed from the generator to make them actionable.

### Where that leaves Phase 3

| Bucket | Count | Nature |
|---|---:|---|
| Mis-routed by input shape | 11 | **fixed here** |
| Declared category without the family's interface | 35 | model-side: implement the interface, or correct the category |
| No supported constructor shape | 54 | scaffold support or manual fixtures |
| Inherits an excluded compositional base | 224 | architectural decision |

The generator no longer misreports anything: every uncovered model now carries an unambiguous, fully-qualified, individually-reasoned diagnostic. The remaining 313 are remediation across the models themselves, which is a different kind of work from fixing the instrument — and the 224 in particular is a decision about whether compositional and wrapper patterns should be auto-constructible at all.

I'd suggest those last three buckets become their own issues rather than being estimated here, and that this one close once #2136 merges — its stated acceptance criteria are met, with the caveat that "the rest of the 1170" was never 1170.
